### ISSUE TITLE
Local variable declareation in templates.

### ISSUE THREAD

**Issue by ismail-codar** [fizzed/rocker#26]
My template like this:
```javascript
fetch(url).then(function(response) {
	response.json().then(function (@raw(SwaggerUtil.responseTypeName(entryValue.getJsonObject("responses")) == "void" ? "" : data)) {
		resolve(@raw(SwaggerUtil.responseTypeName(entryValue.getJsonObject("responses")) == "void" ? "" : data));
	});
})
```
But SwaggerUtil.responseTypeName(.. function calling 2 times.
Can I use it like following
```javascript
@localvar rParam = @SwaggerUtil.responseTypeName(entryValue.getJsonObject("responses"))  == "void" ? "" : data
fetch(url).then(function(response) {
	response.json().then(function (rParam )) {
		resolve(rParam );
	});
})

**Comment by jjlauer** [comment]
Local variable assignment would be a useful feature.  If you wanted to take
a stab at implementing it, I'd be happy to review the PR.

Just one comment on your included code though -- seems like a lot of logic
to put inside a template.  Wouldn't it be cleaner to fetch(url)... in a
controller, get the response, and then call your template with the result?

**Comment by ismail-codar** [comment]
I looked at your code. It looks hard to me. I am not antlr family. Some developer documentation may be usefull.

 I have used rocker in one project. A swagger schema to client generator template is [here](https://github.com/ismail-codar/codegen-maven/blob/master/src/main/resources/views/swagger/qbit/client/typescript/ServiceClient.rocker.html). 

I want to share my views.I also would like to hear your thoughts.

Rocker is very fast and very easy to use. Thanks your work. Especially hot reloading support helped me while developing templates. Otherwise it takes a lot of time.  

According to me {% %} like delimiter used template is more readable. For example
```java
@args (String packageName, String className, Map itemMap)
class YourClass {
@if(some logic) {
some code
}
}
``` 
{ and } are intermixing and readability is falling.

Mostly templates aims multi language usability. Like https://mustache.github.io/ And rocker syntax looks can be adopted different platform. If the authors is not the purpose of this! embedding java codes in template feature would be very useful. Thinking wider rather than local variable assignment. Loops, if else conditions can be used with embedding java code.

**Comment by jjlauer** [comment]
Appreciate your feedback.  It's cool you're using Rocker to help generate a
template that outputs a Java class.

In my opinion, templates should not have much actual logic.  Rocker
supports for loops against your data model, but it sounds like you want for
loops running in embedded Java code as well.  I think that only encourages
putting more logic in your templates than you should.  Plus, templates can
already just call out to other Java code already, so you could pretty
easily put that type of logic in a standard Java utility class as well.
That encourages a better design in my opinion, since it makes unit testing
that kind of logic much easier.  I can see the advantage of supporting
local variable assignment, but I'd be a hard sell on much other embedded
Java code like you suggested.

**Comment by localvar** [comment]
hmmm, just to check why I was @.

**Comment by jjlauer** [comment]
@ismail-codar latest version includes a new `@with` feature that lets you define variables.
