### ISSUE TITLE
Redundant type param of DefaultRockerModel causes generated templates to fail strict compile.

### ISSUE THREAD

**Issue by alkemist** [fizzed/rocker#5]
If you compile with `-Werror`, compilation will fail for any generated template classes because they extend `DefaultRockerModel<T>` but do not specify `T`.

The simplest solution would be to not parameterise `T`, and it looks like it's not currently used.

**Comment by jjlauer** [comment]
@alkemist PRs would be much appreciated.  See my answer to issue #6 for info on compiling rocker w/ -Werror

**Comment by jjlauer** [comment]
So here's the reason there is a parameter.  Rocker supports adding any intermediate parent class to the model or template class hierarchy so that common model/template properties can be supplied for any template.  In order for the builder pattern to work in that case, there needs to be a parameter of the concrete class.

Seems like adding an annotation to ignore this warning is the best way to avoid breaking this feature.

**Comment by alkemist** [comment]
There are no T returning methods on this type though. If a custom super class wants to introduce such API, wouldn't it be up to that type to decide how it wants to implement the pattern.

If you're insistent on keeping the param, it would be better to have the generated classes supply a value for the param than just suppressing the warning.

**Comment by jjlauer** [comment]
@alkemist I revisited the code and I see why you're confused.  Due to the major refactor when hot reloading was supported, it looks like this particular issue was introduced.  You're right the parameter isn't being included, but it should be.  So if you have a model called "A" then the generated class should actually be:

class A extends DefaultRockerModel<A>

The compiler should be changed to output it, rather than what you proposed or my suggestion to suppress the warning.

**Comment by alkemist** [comment]
I'm not sure that I was confused :)

Should it just assumed that the parent type is parameterised for self type? Should this be enforced when specifying a custom parent?
