### ISSUE TITLE
Support for Java 11?

### ISSUE THREAD

**Issue by rseidi** [fizzed/rocker#90]
At my company were using rocker for complex SQL query generation on a critical service, are there any plans to support Java 11?

**Comment by jjlauer** [comment]
Is there a specific issue with Java 11 you are asking about?

**Comment by bendem** [comment]
If it's just that the autodetected version of java is not supported, you can force it by specifying javaVersion to 8 (since nothing was added that depends on 9 or 10). If there is something specific that's not working with java 11, a test case and the error encountered would be helpful.

Seeing as the release cadence for java is increasing, it would probably make sense to think of a better way to handle future java versions than an enum.
